variables:
  BUILD_WORKSPACE: "build"
  CONTAINER_BUILD_IMAGE: "fedora:42"
  CTEST:
    value: "--parallel 16 --schedule-random"
    description: "Here you can set the options for ctest-unittests. By default test involving dbus are excluded since they are not supported inside a container image."
  VERSION_MORE:
    value: "$CI_PIPELINE_IID"
    description: "The forth number of the version string: 1.2.3.X - It is the X. Will be overwritten in main, hotfix or release-branch"
  PARALLEL:
    value: "16"
    description: "Number of parallel jobs for building. Remember: More parallel jobs require more RAM."

workflow:
  name: "Build and test pipeline."

######################################
# Templates
######################################

# Required for the publish Doxygen stage to find the defined $HTML variable.
include:
  - project: "devops/docker"
    file: "/templates/global.yml"

  - component: $CI_SERVER_FQDN/infrastructure/ppos/rpm-gitops/publish-n62@1.4.1
    inputs:
      rpm_build_job_name: "build (s)rpm"
      rpm_base_path: "$BUILD_WORKSPACE/RPM"

# Prevents all jobs that extend this stage will not run during nightly builds.
.to_manual_rule_template:
  extends:
    - .container_image_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Run for merge requests...
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS # ... but not for a push inside a open merge request to avoid duplicate runs
      when: never
    - if: $CI_COMMIT_BRANCH  && $CI_PIPELINE_SOURCE != "schedule"

# Used to also skip manual duplicate CI runs when pushing to a PR.
.skip_manual_for_pr_template:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Allow running for merge requests...
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS # ... but not for a push inside a open merge request to avoid duplicate runs
      when: never
    - if: $CI_COMMIT_BRANCH  && $CI_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true

# Will run nightly if not set to build manually.
.container_image_template:
  image:
    name: $CONTAINER_BUILD_IMAGE
    pull_policy: always
  timeout: 30 minutes # Default job timeout
  before_script:
    - dnf install -y -q boost-devel cmake cppcheck clang clang-analyzer clang-tools-extra gcc gcc-c++ git gtest gtest-devel pkgconf-pkg-config dbus-libs dbus-devel libstdc++ 2>&1 1>/dev/null
    - git config --global user.name gitlab-ci
    - git config --global user.email noreply@localhost
  tags:
    - container

# Default template where all jobs that extend this will not run during nightly builds.
.container_image_no_nightly_run_template:
  extends:
    - .container_image_template
    - .to_manual_rule_template

######################################
# Stages
######################################

stages:
  - "🏗️ Build Stage 1"
  - "🚧 Build Stage 2"
  - "🧪 Test"
  - "📦 Release"
  - "🌃 Nightly"

######################################
# 🏗️ Build Stage 1
######################################

# GCC Release Build Tests=OFF
build release gcc:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🏗️ Build Stage 1"
  script:
    - rm -rf $BUILD_WORKSPACE # Ensure we start clean
    - cmake . -B $BUILD_WORKSPACE -DAPS_CHRONY_DBUS_SERVICE_FETCH_CONTENT_USE_GITLAB_CI_TOKEN=ON -DCMAKE_BUILD_TYPE=Release -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=OFF
    - cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_SHORT_SHA}"
    expose_as: "Release Build"
    paths:
      - $BUILD_WORKSPACE

# GCC Debug Build Tests=OFF
build debug gcc:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🏗️ Build Stage 1"
  script:
    - rm -rf $BUILD_WORKSPACE # Ensure we start clean
    - cmake . -B $BUILD_WORKSPACE -DAPS_CHRONY_DBUS_SERVICE_FETCH_CONTENT_USE_GITLAB_CI_TOKEN=ON -DCMAKE_BUILD_TYPE=Debug -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=OFF
    - cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_SHORT_SHA}"
    expose_as: "Debug Build"
    paths:
      - $BUILD_WORKSPACE

# GCC Release Build Tests=ON
build release test gcc:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🏗️ Build Stage 1"
  script:
    - dnf install -y chrony dbus-daemon systemd
    - rm -rf $BUILD_WORKSPACE # Ensure we start clean
    - cmake . -B $BUILD_WORKSPACE -DAPS_CHRONY_DBUS_SERVICE_FETCH_CONTENT_USE_GITLAB_CI_TOKEN=ON -DCMAKE_BUILD_TYPE=Release -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=ON
    - cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
    - cd $BUILD_WORKSPACE
    - . ../tests/setupenv.sh
    - $BUILD_WORKSPACE/src/chrony-dbus-service &
    - ctest $CTEST
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - $BUILD_WORKSPACE

######################################
# 🚧 Build Stage 2
######################################

# Build (S)RPM
build (s)rpm:
  extends:
    - .container_image_template
    - .skip_manual_for_pr_template
  stage: "🚧 Build Stage 2"
  script:
    - sudo dnf install -y rpmdevtools systemd-rpm-macros selinux-policy-devel
    - sed -i "s/set(CPACK_RPM_PACKAGE_RELEASE \"[0-9]\+\")/set(CPACK_RPM_PACKAGE_RELEASE \"${CI_PIPELINE_IID}\")/" packaging/rpm/cpack_config.cmake
    - cmake . -B $BUILD_WORKSPACE -DAPS_CHRONY_DBUS_SERVICE_FETCH_CONTENT_USE_GITLAB_CI_TOKEN=ON -DCMAKE_BUILD_TYPE=Release -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=OFF -DAPS_CHRONY_DBUS_SERVICE_CPACK_RPM_TYPE=RPM
    - cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
    - pushd $BUILD_WORKSPACE
    - ../scripts/build_rpm.sh
    - popd
    - cp -r ./packaging/selinux/ $BUILD_WORKSPACE/
    - pushd $BUILD_WORKSPACE/selinux/
    - ../../scripts/build_selinux_policy.sh
    - mv noarch/*.rpm ..
    - popd
    - mkdir -p $BUILD_WORKSPACE/RPM
    - rm -rf $BUILD_WORKSPACE/RPM/*
    - mv $BUILD_WORKSPACE/*.rpm $BUILD_WORKSPACE/RPM
  needs: []
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_SHORT_SHA}"
    expose_as: "Release Build S_RPM"
    paths:
      - $BUILD_WORKSPACE/RPM/

# Build Doxygen Docs
build doxygen:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🚧 Build Stage 2"
  script:
    - sudo dnf install -y doxygen plantuml
    - chmod 777 scripts/*.sh
    - scripts/doxygen.sh
    - cd $BUILD_WORKSPACE/doxygen/
    - tar -zcf doxygen.tar.gz html/
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_SHORT_SHA}"
    expose_as: "Doxygen"
    paths:
      - $BUILD_WORKSPACE/doxygen/doxygen.tar.gz
  needs: []

# Debug Build All Sanitizers Tests=ON
build debug all sanitizers test:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🚧 Build Stage 2"
  script:
    - dnf install -y chrony dbus-daemon systemd
    - rm -rf $BUILD_WORKSPACE # Ensure we start clean
    - cmake . -B $BUILD_WORKSPACE -DAPS_CHRONY_DBUS_SERVICE_FETCH_CONTENT_USE_GITLAB_CI_TOKEN=ON -DCMAKE_BUILD_TYPE=Debug -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=ON -DAPS_CHRONY_DBUS_SERVICE_DEBUG_SANITIZER_FLAG_ALL=ON
    - cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
    - cd $BUILD_WORKSPACE
    - . ../tests/setupenv.sh
    - $BUILD_WORKSPACE/src/chrony-dbus-service &
    - ctest $CTEST
  needs: # Depend only on gcc since we are using just gcc sanitizers right now
    - "build release gcc"
    - "build debug gcc"
    - "build release test gcc"

# Release Build Thread Sanitizers Tests=ON
build debug thread sanitizers test:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🚧 Build Stage 2"
  script:
    - dnf install -y chrony dbus-daemon systemd
    - rm -rf $BUILD_WORKSPACE # Ensure we start clean
    - cmake . -B $BUILD_WORKSPACE -DAPS_CHRONY_DBUS_SERVICE_FETCH_CONTENT_USE_GITLAB_CI_TOKEN=ON -DCMAKE_BUILD_TYPE=Debug -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=ON -DAPS_CHRONY_DBUS_SERVICE_DEBUG_SANITIZER_FLAG_THREAD=ON
    - cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
    - cd $BUILD_WORKSPACE
    - . ../tests/setupenv.sh
    - $BUILD_WORKSPACE/src/chrony-dbus-service &
    - ctest $CTEST
  needs: # Depend only on gcc since we are using just gcc sanitizers right now
    - "build release gcc"
    - "build debug gcc"
    - "build release test gcc"

######################################
# 🧪 Test
######################################

# Test Doxygen Docs Build
build doxygen test:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🧪 Test"
  script:
    - sudo dnf install -y doxygen pipx plantuml
    - export PATH=$PATH:/root/.local/bin
    - pipx install doxygen-junit
    - chmod 777 scripts/*.sh
    - scripts/doxygen.sh || true
    # Fix the file path references so they are relative to the blob and not the buildspace. We use ; as the substitute so don't have to escape every forwardslash
    - sed -i "s;$CI_PROJECT_DIR/src;src;g" $BUILD_WORKSPACE/doxygen/doxygen_warnings.log || exit 1
    - sed -i "s;$CI_PROJECT_DIR/test;test;g" $BUILD_WORKSPACE/doxygen/doxygen_warnings.log || exit 1
    - doxygen_junit --input $BUILD_WORKSPACE/doxygen/doxygen_warnings.log --output $BUILD_WORKSPACE/doxygen/doxygen_junit.xml || exit 1
    - cat $BUILD_WORKSPACE/doxygen/doxygen_junit.xml
    - grep -iq "<error " "$BUILD_WORKSPACE/doxygen/doxygen_junit.xml" && exit 1 || exit 0
  needs:
    - "build doxygen"
  artifacts:
    reports:
      junit: $BUILD_WORKSPACE/doxygen/doxygen_junit.xml
    when: always

# cppcheck
cppcheck:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🧪 Test"
  timeout: 60 minutes
  script:
    - sudo dnf install -y pipx
    - export PATH=$PATH:/root/.local/bin
    - pipx install cppcheck-codequality
    - rm -rf $BUILD_WORKSPACE # Ensure we start clean
    - cmake . -B $BUILD_WORKSPACE -DAPS_CHRONY_DBUS_SERVICE_FETCH_CONTENT_USE_GITLAB_CI_TOKEN=ON -DCMAKE_BUILD_TYPE=Debug -DAPS_CHRONY_DBUS_SERVICE_ENABLE_CPPCHECK=ON -DAPS_CHRONY_DBUS_SERVICE_ENABLE_CPPCHECK_EXHAUSTIVE=ON
    - cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
    # Convert to a Code Climate quality JSON report
    - cppcheck-codequality --input-file $BUILD_WORKSPACE/cppcheck.xml --output-file $BUILD_WORKSPACE/cppcheck_report.json
    # Fix the file path references so they are relative to the blob and not the buildspace. We use ; as the substitute so don't have to escape every forwardslash
    - sed -i "s;$CI_PROJECT_DIR/src;src;g" $BUILD_WORKSPACE/cppcheck_report.json
    - sed -i "s;$CI_PROJECT_DIR/test;test;g" $BUILD_WORKSPACE/cppcheck_report.json
    - cat $BUILD_WORKSPACE/cppcheck.xml
    - if [ $(grep -ic "<error " $BUILD_WORKSPACE/cppcheck.xml) -gt 0 ]; then exit 1; fi
  artifacts:
    reports:
      codequality: $BUILD_WORKSPACE/cppcheck_report.json
    when: always
  needs: []

# clang-tidy
clang-tidy:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🧪 Test"
  timeout: 60 minutes
  script:
    - rm -rf $BUILD_WORKSPACE # Ensure we start clean
    - cmake . -B $BUILD_WORKSPACE -DAPS_CHRONY_DBUS_SERVICE_FETCH_CONTENT_USE_GITLAB_CI_TOKEN=ON -DCMAKE_BUILD_TYPE=Debug -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=ON -DAPS_CHRONY_DBUS_SERVICE_ENABLE_CLANG_TIDY=ON
    - cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
  needs: []

# clang-format
clang-format:
  extends:
    - .container_image_no_nightly_run_template
  stage: "🧪 Test"
  script:
    - clang-format --version
    - ./scripts/check_clang_format.sh tests src
  needs: []

lint-rpm:
  stage: "🧪 Test"
  extends:
    - .container_image_no_nightly_run_template
  tags:
    - docker
  script:
    - sudo dnf install -y rpmlint
    - rpmlint -c rpmlint_fedora.toml -s SPECS/chrony-dbus-service.spec
######################################
# 📦 Release
######################################

######################################
# 🌃 Nightly
######################################
