## Continuous integration for chrony-dbus-service

name: chrony-dbus-service-ci
on: [push, workflow_dispatch]
env:
  PROJECT_NAME: ${{ github.repository }}
  BUILD_WORKSPACE: build
jobs:
  build-doxygen:
    uses: ./.github/workflows/doxygen.yaml
  clang-format:
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - name: pepare-git
        run: |
          dnf install -y -q git 2>&1 1>/dev/null
          git config --global user.name github-actions
          git config --global user.email github-actions@users.noreply.github.com
      - name: Checkout
        uses: actions/checkout@v5
      - name: clang-format-run
        id: clang-format-run
        run: |
          echo "${{ github.action }}: Installing dependencies"
          dnf install -y -q clang clang-analyzer clang-tools-extra libstdc++ 2>&1 1>/dev/null
          clang-format --version
          echo "${{ github.action }}: Running scripts/check_clang_format.sh"
          ./scripts/check_clang_format.sh tests src
  tests:
    uses: ./.github/workflows/tests.yaml
  clang-tidy:
    uses: ./.github/workflows/cmake-gcc.yaml
    with:
      CMAKE_PARAMS: -DCMAKE_BUILD_TYPE=Debug -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=ON -DAPS_CHRONY_DBUS_SERVICE_ENABLE_CLANG_TIDY=ON
  build-rpm:
    uses: ./.github/workflows/rpm.yaml
  cppcheck:
    uses: ./.github/workflows/cppcheck.yaml
