## Builds the cmake project with CPPCHECK_EXHAUSTIVE=ON and runs cppcheck-codequality

name: cppcheck
on: [workflow_call]
jobs:
  cppcheck-build:
    uses: ./.github/workflows/cmake-gcc.yaml
    with:
      CMAKE_PARAMS: -DCMAKE_BUILD_TYPE=Debug -DAPS_CHRONY_DBUS_SERVICE_ENABLE_CPPCHECK=ON -DAPS_CHRONY_DBUS_SERVICE_ENABLE_CPPCHECK_EXHAUSTIVE=ON
  cppcheck-run:
    needs: cppcheck-build
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      env:
        PROJECT_NAME: ${{ github.repository }}
        BUILD_WORKSPACE: build
    steps:
      - name: pepare-git
        run: |
            dnf install -y -q git 2>&1 1>/dev/null
            git config --global user.name github-actions
            git config --global user.email github-actions@users.noreply.github.com
      - name: Checkout
        uses: actions/checkout@v5
      - name: run-cppcheck
        id: run-cppcheck
        run: |
          echo "${{ github.action }}: Installing dependencies"
          dnf install -y -q cppcheck 2>&1 1>/dev/null
          # TODO: is cppcheck-codequality required here?
          #echo "Running cppcheck-codequality"
          #cppcheck-codequality --input-file $BUILD_WORKSPACE/cppcheck.xml --output-file $BUILD_WORKSPACE/cppcheck_report.json
          # Fix the file path references so they are relative to the blob and not the buildspace. We use ; as the substitute so don't have to escape every forwardslash
          #sed -i "s;${PROJECT_NAME}/src;src;g" $BUILD_WORKSPACE/cppcheck_report.json
          #sed -i "s;${PROJECT_NAME}/test;test;g" $BUILD_WORKSPACE/cppcheck_report.json
          if [ $(grep -ic "<error " $BUILD_WORKSPACE/cppcheck.xml) -gt 0 ]; then exit 1; fi
      - name: cppcheck-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck
          path: $BUILD_WORKSPACE/cppcheck_report.json
