## Builds the cmake project with BUILD_TESTS=ON and runs the tests with ctest

name: run-tests
on:
  workflow_call:
    inputs:
      TEST_PARAMS:
        description: Parameters passed to ctest
        type: string
        default: --parallel 16 --schedule-random
env:
  PROJECT_NAME: ${{ github.repository }}
  BUILD_WORKSPACE: build
  CTEST: ${{ inputs.TEST_PARAMS }}
jobs:
  ctest:
    runs-on: ubuntu-latest
    container:
      image: fedora:41

    steps:
      - name: Install Dependencies
        id: install-dependencies
        run: |
          echo "${{ github.action }}: Installing dependencies"
          dnf install -y -q rpmdevtools boost-devel cmake clang clang-analyzer clang-tools-extra gcc gcc-c++ gtest gtest-devel pkgconf-pkg-config dbus-libs dbus-devel libstdc++ 2>&1 1>/dev/null
      - name: pepare-git
        run: |
          dnf install -y -q git 2>&1 1>/dev/null
          git config --global user.name github-actions
          git config --global user.email github-actions@users.noreply.github.com
      - name: Checkout
        uses: actions/checkout@v5
      - name: build-tests
        id: build-tests
        run: |
          git config --global --add safe.directory "$(pwd)" # Ensure the ownership of the .git directory is OK
          rm -rf $BUILD_WORKSPACE # Ensure we start clean
          echo "${{ github.action }}: Running cmake . -B"
          cmake . -B $BUILD_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DAPS_CHRONY_DBUS_SERVICE_BUILD_TESTS=ON
          echo "${{ github.action }}: Running cmake --build"
          cmake --build $BUILD_WORKSPACE --parallel $PARALLEL
      - name: run-ctest
        id: run-ctest
        run: |
          echo "${{ github.action }}: Installing dependencies"
          dnf install -y -q cmake gtest chrony dbus-libs dbus-daemon 2>&1 1>/dev/null
          cd $BUILD_WORKSPACE
          chmod u+x ../tests/setupenv.sh
          ../tests/setupenv.sh
          ./src/chrony-dbus-service &
          sleep 10 # give chronyd time to initialize
          ctest $CTEST
